Actually create temporary directories on *nix
vector-of-bool/dds pull request #129
Opened 2022-05-31 10:08 UTC by maxtruxa

`mktemp` doesn't actually create the directory and is [pretty broken on some platforms](https://man7.org/linux/man-pages/man3/mktemp.3.html#BUGS). `mkdtemp`, `mkstemp` and friends are here to fix this.

2022-06-09 23:33 UTC, vector-of-bool commented
Thank you for your patience, and thank you for the contribution! I had not noticed that mktemp was utterly broken, but was noticing some transient trouble with temporary directories, and this could explain those issues.

It looks like `mkdtemp` is not available on macOS (at least in the CI environment), and directory creation is failing in a Linux test. The failure on Windows is unrelated and is my own fault, so you can ignore that one.

2022-06-09 23:39 UTC, vector-of-bool requested changes
Thank you for your contribution!

I've added notes on how I believe the CI build can be fixed. (Ignore the Windows failure, that's unrelated.)

2022-06-09 23:39 UTC, vector-of-bool commented on src/bpt/temp.nix.cpp
> +    const char* tempdir_path = ::mkdtemp(templ.data());
As long as the `std::string` is non-`const`, you can call `.data()` to get a pointer-to-modifiable `char`, which should work here without needing to create a vector of characters.

This also seems to fail if the parent directory does not already exist. Add a call to `fs::create_directories(base)` beforehand and that should mitigate the issue.

It also seems there is a missing `#include <unistd.h>` for macOS to see `mkdtemp()`.

2022-06-15 12:30 UTC, maxtruxa commented
The `data()` thing was apparently changed with C++17. The more you know! I guess I'll have to up my modern C++ game.

2022-06-15 18:10 UTC, merged